# Generated by Django 4.2.4 on 2023-08-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_else_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_referral_code_activated',
        ),
    ]
