---
version: "3.9"

services:

  api:
    build:
      context: .
#    image: yuryyury/hammer_system
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - /home/yury/SkyPro/test_task/hammer_system_2/.env:/todolist/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
#    image: yuryyury/hammer_system
    container_name: migrations
    volumes:
      - /home/yury/SkyPro/test_task/hammer_system_2/.env:/todolist/.env

    command: python3 manage.py migrate

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:15.0-alpine

      environment:
#        POSTGRES_DB: ${DB_NAME}
#        POSTGRES_USER: ${DB_USER}
#        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: hammer_system
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

      restart: always

      container_name: postgres

      volumes:
        - /home/yury/SkyPro/test_task/hammer_system_2/postgresdata:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 5s
        timeout: 5s
        retries: 15
...